# Generated by Django 5.0.7 on 2024-07-12 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laporan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kpp",
                    models.CharField(
                        choices=[
                            (
                                "Prakatama Jakarta Tanah Abang Tiga",
                                "Prakatama Jakarta Tanah Abang Tiga",
                            )
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "wp",
                    models.CharField(
                        choices=[
                            ("Badan", "Badan"),
                            ("Op Karyawan", "Op Karyawan"),
                            ("Op Non Karyawan", "Op Non Karyawan"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "spt",
                    models.CharField(
                        choices=[
                            ("SPT PPH Badan", "Spt Pph Badan"),
                            ("SPT PPH Op 1770", "Spt Pph Op 1770"),
                            ("SPT PPH Op 1770S", "Spt Pph Op 1770S"),
                            ("SPT PPH Op 1770SS", "Spt Pph Op 1770Ss"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Kurang Bayar", "Kurang Bayar"),
                            ("Lebah Bayar", "Lebih Bayar"),
                            ("Nihil", "Nihil"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "kanal",
                    models.CharField(
                        choices=[
                            ("DPC Web Service", "Dpc Web Service"),
                            ("SPTXML", "Sptxml"),
                            ("E-Filing", "E Filing"),
                            ("E-Filing pajak.go.id", "E Filing Pajak Dot Go Id"),
                            ("E-Form", "E Form"),
                            ("E-SPT Tahunan yang Baru", "E Spt Tahunan Yang Baru"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("Pertanian, Kehutanan, dan Peri...", "A"),
                            ("Pertambangan dan Penggalian", "B"),
                            ("Industri Pengolahan", "C"),
                            ("Pengadaan Listrik, Gas, UAP/A...", "D"),
                            ("Treatment Air", "E"),
                            ("Konstruksi", "F"),
                            ("Perdagangan Besar dan Eceran", "G"),
                            ("Pengangkutan dan Pergudangan", "H"),
                            ("Penyediaan Akomodasi dan Peny", "I"),
                            ("Informasi dan Komunikasi", "J"),
                            ("Aktivitas Keuangan dan Asuran", "K"),
                            ("Real Estat", "L"),
                            ("Aktivitas Profesional, Ilmiah", "M"),
                            ("Aktivitas Penyewaan dan Sewa", "N"),
                            ("Administrasi Perintahan Pe", "O"),
                            ("Pendidikan", "P"),
                            ("Aktivitas Kesehatan Manusia Da", "Q"),
                            ("Kesenian, Hiburan, dan Rekreasi", "R"),
                            ("Aktivitas Jasa Lainnya", "S"),
                            ("Aktivitas Rumah Tangga Sebagai", "T"),
                            ("Aktivitas Badan Internasional", "U"),
                            ("Pejabat Negara, Karyawan, Pen", "Z"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "bulan",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "tahun",
                    models.IntegerField(
                        default=2024,
                        validators=[django.core.validators.MaxValueValidator(2024)],
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("npwp", models.CharField(max_length=15)),
                ("pendapatan", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "kepatuhan",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
